### ISSUE TITLE
WMA Files not showing in the "Browse Files"

### ISSUE THREAD

**Issue by tacul** [devsnd/cherrymusic#378]
I have already set the mplayer exec to my path.

The server is working under Windows7

**Comment by Mootch** [comment]
I know this issue is old and closed, but I am running the devel version on my raspberry pi with compiled ffmpeg (./configure, make, make install) and my wma files are not showing up in the "Browse Files". I just started using cherrymusic, so I don't know if a change caused this or if it's due to my set-up. Are there any other settings that I need to change?

**Comment by devsnd** [comment]
Hi Mootch,

I just added a feature to list the encoders and decoders available to cherrymusic. So get the latest devel release and issue the following command:

    cherrymusic --info

This should list all the encoders and decoders as well as the filetypes supported. You can paste the output here so we can debug your problem further. :alien:

**Comment by Mootch** [comment]
Alright, here is what I got. 

```
CherryMusic Server 0.34.1+devel-36-g04cdc30

CherryPy: 3.2.2
Python: CPython 3.2.3
Platform: Linux-3.18.3+-armv61-with-debian-7.8

configuration dir:
    /home/pi/.config/cherrymusic
server data dir:
    /home/pi/.local/share/cherrymusic
static resources dir:
    /home/pi/cherrymusic/
server package dir:
    /home/pi/cherrymusic/cherrymusicserver
process working dir:
    /home/pi/cherrymusic

locale: ('en_US', 'UTF-8'), default: ('en_US', 'UTF-8')
filesystem encoding: utf-8

Available Decoders:
    mp3 (ffmpeg)
    wma (ffmpeg)
    ogg (ffmpeg)
    wav (cat)
Available Encoders:
    wav (cat)
```

Thanks for the help!

**Comment by devsnd** [comment]
You need to install `lame` and/or `vorbis`, because ffmpeg only provides the decoders necessary to read WMA files, but cherrymusic still needs to encode the raw audio data back to mp3 or ogg for your browser to be able to play it.

So on debian all you need to do is:

    apt-get install lame vorbis-tools

And then restart CM.

I'll close the issue for now, but if there's still a problem after installing those, feel free to reopen it.

**Comment by Mootch** [comment]
I installed those and re-did the cherrymusic install, then the .wma files were viewable and playable. However, during all this I noticed that the .wma files showed up when I manually start cherrymusic, but don't show up when it starts from crontab. Do you know if there is any way to address this?

I also tried the Debian Daemon script. I had some permission errors, but when I got around them, the .wma files did not show up again.

**Comment by devsnd** [comment]
Are you running the cronjob using the same user as with your manual start?

If not, please try that; It should give the same results then. See this [post on StackOverflow on how to allow crontabs for non root users](https://unix.stackexchange.com/questions/131145/debian7-cron-allow-cron-deny-files) if it isn't set up like this already.

Otherwise make sure that `lame` and `oggenc` (vorbis-tools) are available to whatever user which runs the cronjob.

**Comment by Mootch** [comment]
I am trying both as the "pi" user. When I check the $PATH variable as the "pi" user, it lists the folder that contains `lame` and `oggenc`.

Thanks again for the help.

**Comment by devsnd** [comment]
Well, I'm out of ideas for debugging this remotely, sorry. :crying_cat_face: 

Maybe you can instead just [start cherrymusic in a screen session](https://github.com/devsnd/cherrymusic/wiki/Setup-guide#running-in-a-gnu-screen-session), this should be the exact same environment as when started manually. :hand: And if you dont restart your pi too often this wouldn't be such a huge hassle.

**Comment by 6arms1leg** [comment]
... or, since you are running debian on a rpi, check out this blog [post](http://fomori.org/blog/?p=687).

**Comment by tilboerner** [comment]
@Mootch, could you make sure the misbehaving cherrymusic is running with the correct user and PATH? To check:

    $ cat /proc/<PID>/environ | tr \\0 \\n | grep -E "^PATH=|^USER="

where `<PID>` is the process id of cherrymusic. (You can get that with `pgrep -f cherrymusic`, for example.) If you get denied permission, run with root privileges, e.g. `sudo`.

If there's no output for USER, you can get the user name with:

    $ ps -eo euser,ruser,suser,fuser,cmd | grep cherrymusic

(This should be 4 times the same user name for effective, real, saved and filesystem user respectively.)

**Comment by Mootch** [comment]
@tilboerner  `pgrep` for my user gave me nothing. `sudo pgrep` gave me 2099, 2100, 2411.

`$ cat /proc/<PID>/environ | tr \\0 \\n | grep -E "^PATH=|^USER="` showed the following paths for the PIDs:
2099: `/usr/bin:/bin`
2100: `/usr/bin:/bin`
2411: `/proc/2411/environ: No such file or directory`

`$ ps -eo euser,ruser,suser,fuser,cmd | grep cherrymusic` gave me my user name for `/bin/sh -c python3` and `python3` and `grep`

@devsnd @6arms1leg I will check out the blog post that includes running in `screen` when I get more time to mess around.
