### ISSUE TITLE
Unable to generate thumbnail for long file paths

### ISSUE THREAD

**Issue by lzh9102** [devsnd/cherrymusic#509]
## Problem Description

I'm using CherryMusic on an ArchLinux server (kernel 3.13.8). When browsing a collection of albums in the same directory, I found that the album art for some of the folders failed to show up. The exception thrown was

```
OSError: [Errno 36] File name too long
```

To reproduce this problem, please create a very deep directory structure in the music directory (e.g.

```
/autofs-mount/raid1/storage/home/local-users/cherrymusic-user/cherrymusic-music-directory/2014-fall-albums/animation-albums/popular-albums/five-star-albums/[13579246810]super_album_by_some_pop_star
```

) and put an image there. Next, open the browser, connect to cherrymusic and browse to the directory with the image. The image will not show up.

The reason for this behavior is because the filename for the thumbnail is generated by base64-encoding the album path:

```python
# cherrymusicserver/pathprovider.py line 125
configpath = os.path.join(albumartcachepath, base64encode(directorypath))
```

The length of `base64encode(directorypath)` is proportional to the number of bytes in `directorypath`.
When `directorypath` is long enough, the resulting `configpath` may exceed the longest filename allowed by the OS, making it impossible to save the generated thumbnail to disk.

## Proposed Solution

I would suggest using cryptographic hash functions like `hashlib.sha256()` to generate the albumart filename from the album path, just like what git does for commit ids. The outputs of the hash functions are fixed-length while being very unlikely to collide for different inputs. I have already modified my instance to use `sha256()` and used it for 2 days: https://github.com/lzh9102/cherrymusic/commit/4af9080152029ba182a4df33b761d8cf284860e4. I think it would be great to have the issue fixed upstream.

When considering backward-compatibility,
there is a chance, altough unlikely, that when a CherryMusic instance upgrades to the hash-based version, the hash of a certain albumart will be the same as an existing base64-encoded albumart, causing the wrong image to be loaded. If that is a concern, you can add some characters outside the base64-alphabets `[a-zA-Z/+=]` to the albumart filename (e.g. `albumartpath = os.path.join(albumartcachepath, computeHash(directorypath) + ".thumb"`), then the resulting albumart filename will never collide with existing base64-encoded albumart.

**Comment by tilboerner** [comment]
Hi @lzh9102, thanks for the clear and detailed description. Using a collision-resistant hash function like SHA-256 to generate fixed-length ids is a very good solution, I think.

Changing the naming scheme invalidates all existing names, so we can just delete all the existing files to avoid any collision problems between old and new names. However, this observation leads to a more serious issue with backward compatibility:

The album art directory isn't just a cache for images that reside somewhere in the music directory; it also stores images that were downloaded via the album art search function. All these images, and the work that went into selecting them, will be lost when the names change.

So, for an acceptable solution, we must preserve the existing data, and convert old names to new ones. This should happen automatically. Unfortunately, we have no concept yet for such migrations (outside of the database), so the necessary functionality must be created first.

Here's what's needed in this particular case:

1. A way to reliably differentiate between schemes.

    I propose a file named `.version` inside the album art folder that contains a version string to identify the naming scheme in use. A missing file implies `None`, which implies version `0` or `0.0` or whatever.

    The initial `.` in the name serves to mark the file as hidden, hinting at its meta nature. It's also not in the output alphabet of either naming scheme, which protects the file from naming collisions.

2. A script to convert between versions.

    It should be careful to leave the album art in a consistent state (i.e., the prior state) in case something goes wrong.

3. A mechanism for CherryMusic to detect if an action is needed to continue,
    and to either perform it itself (preferable), or prompt the user for it.


So, yeah, we need a general migration mechanism; but maybe we can tackle this issue in a way which can be later integrated into such a thing.

**Comment by lzh9102** [comment]
I implemented a (standalone) script/module to migrate the albumart cache to the new format: https://gist.github.com/lzh9102/351c72e2c0a7a5fef1a5. It tries to rename all base64-encoded files inside the given directory to their sha256 counterparts. If any rename fails (e.g. permission denied), all previous renames are undone, restoring the directory to the original state.

This satisfies the 2nd need

>A script to convert between versions.
> 
>It should be careful to leave the album art in a consistent state (i.e., the prior state) in case something goes wrong.

Here's an example usage

### before migration
```
$ tree -a albumart
albumart
├── MjAxMC0xMC0yNyDlsJHlpbPmmYLku6MgLSBIb290KEVQKQ==
├── QUNHL1RvSGVhcnQy
├── QUNHL+OBguOBo+OBoeOBk+OBo+OBoQ==
├── QUNHL+OCouOCr+OCu+ODq+ODu+ODr+ODvOODq+ODiQ==
└── QUNHL+WkieaFi+eOi+WtkOOBqOeskeOCj+OBquOBhOeMqw==

0 directories, 5 files
```

### migrate albumart directory
```
$ ./migrate.py albumart
migrated 5 files
```

### after migration
```
$ tree -a albumart
albumart
├── 09d10b54df4c803ff98282a1bd9ce82e97e3ce8b5d3f374f4931b4fc85706f74.thumb
├── 2c58b40f653ce8b52e6919eec5c4cf3dc2f5eb0e9549f068aaa1a3e849318b9e.thumb
├── 3ec7cf359912d470b393269b41dea3079e8e59bca4b62030bc4fafbe9ef30093.thumb
├── 66750257cbae49db6fb0c86571ba8a66c195a9cc40e5020effab4fd3764038af.thumb
├── face04439c0f25317482e234be1b7e056ded2b261e7784c095ad179a58ddb635.thumb
└── .version

0 directories, 6 files
$ cat albumart/.version
1
```

Next I'll try to find a way to test this module automatically.

**Comment by devsnd** [comment]
Hi Che-Huai Lin,

Thanks for the detailed report and also the proposed fix for the problem!

@tilboerner I think your proposition of creating versioning for the problem is overkill, especially since a the hash function is not reversable, so there is no way back anyway. I think however that the hidden file is the most straight forward solution to detect which of the two albumart path schemas are currently used or rather, to detect if a migration should be performed.

So if there is a file called `.hashpath` in the albumart directory, CM will start-up normally. If there isn't, CM will migrate the filenames, by traversing over all the files inside the albumart directory and rename each file using a hash function instead of the base64 encoded filename.

Furthermore, I think it's a great idea to add some character that is not used by the base64 alphabet to the filename to make sure that this renaming can only be executed once. (The proposed `.thumb` extension would do that for us). That means, that if you kill the process while migrating, and then start CM again, the process would just continue without trying to migrate anything twice.

Also, there is already a place where those kind of pre-startup migrations should be located: the `cmbootstrap` module already contains a fix for something OSX related. So adding a method to the `Migrations` class would be most sensible. I've written a quick implementation of how I think this could be done (i've not tried the code, so maybe it doesn't work at all ;)

    def migrate_albumart_to_hashpath():
        import os, shutil, base64, codecs, hashlib
        from cherrymusicserver import pathprovider
        artfolder = pathprovider.albumArtFilePath('')
        hashpathfile = os.path.join(artfolder, '.hashpath')
        if os.path.exists(hashpathfile):
            return  # files were already migrated

        def base64decode(name):
            # decode from the old naming scheme
            return codecs.decode(base64.b64decode(name), 'UTF-8')

        def hashencode(name):
            # encode to the new scheme. This should actually
            # be the new implementation from pathprovider
            utf8_bytestr = codecs.encode(s, 'UTF-8')
            return hashlib.md5(utf8_bytestr).hexdigest()

        for f in os.listdir(artfolder):
            if f.startswith('.'):
                continue  # don't try migrating the .hashpath file
            try:
                oldpath = os.path.join(artfolder, f)
                newpath = os.path.join(artfolder, hashencode(base64decode(f)))
                shutil.move(oldpath, newpath)
            except:
                # the file was already migrated
                # (base64 could not decode the '.thumb' extension)
                pass
        # migration is finished, so create .hashpath file
        open(hashpathfile, 'a').close()


Also, you might have noticed that in my proposed implementation I replaced the sha512 with md5. Since this essentially a hashtable lookup, we don't need a cryprographically secure hash function. All we need is to make sure that there are no collisions and md5 is more than enough for that. Keep in mind that many people run cherrymusic on their raspberrypis and equally low-powered SOCs where this makes a big difference.

Any other suggestions?

**Comment by tilboerner** [comment]
@lzh9102:

Thanks a lot for taking the time to write a script! I only had a look at @devsnd's so far, which prompted some investigations on my own, and I didn't have the time yet to look at yours. But I'll look at it next thing.

The following are some observations I've come up with so far.


@devsnd:

> I think your proposition of creating versioning for the problem is overkill

Yes, but not by very much. :) I started out with an empty file as well, but figured, in case we need to touch this again... But I guess we can still take that step *if* we ever need to come back to it.


> the hash function is not reversable, so there is no way back anyway

There is a way back as long as we have a list of paths to try, but it's very cumbersome. Still, basically you're right, and it's good that you mention it. It means that the next time we need, or merely want, to change how this data is stored, we won't have it as easy. (May that day never come!) Do you think we should do something about it now? That manually picked album art *is* valuable data, after all.


You're also right in the sense that, in case of error, it's not necessary to leave the album art in the prior state (as I said). It's good enough to be able to pick up where we left off. @lzh9102, sorry for the extra work because I didn't realize it sooner! @devsnd, your idea:

> to add some character that is not used by the base64 alphabet to the filename to make sure that this renaming can only be executed once

is very likable because it's so simple, but it means relying on a side effect that remains a bit obscure in the code. There are some related issues which I mention below.


> I replaced the sha512 with md5 [...] make sure that there are no collisions and md5 is more than enough for that

Goodie. I was wondering about that. I've looked up the probabilities by now, and the internet [seems to agree](http://en.wikipedia.org/wiki/Birthday_attack#Mathematics). :)


> place where those kind of pre-startup migrations should be located: the `cmbootstrap` module

Oh, I never! I always thought that's just to pull dependencies into the local installation. It's also a separate package from `cherrymusicserver`, so it's quite far removed from the code the migration is meant for. I can see the appeal of using the existing infrastructure, but I think it would be better to put that code somewhere else.

----

Some remarks about the code. In general, I like the simplicity of it, but there are some details which I think still need to be addressed:

* `base64.b64decode` seems to silently ignore invalid characters, so strings containing any of those can still decode. (`base64.b64decode('FFF.thumb')` is an example.) It think it's safer to test for invalid characters directly and then conclude that the filename can't be migrated. This might mean it's already a new name; it might also warrant an error or warning message.

* Target filenames might exist if the migration loop can run concurrently with the server or other instances of itself. This would raise an [error on Windows](https://docs.python.org/2/library/os.html#os.rename), because [`shutil.move` defaults to `os.rename`](https://docs.python.org/2/library/shutil.html#shutil.move) in our case.

* If the server is allowed to run before the migration is successfully finished, we can't be sure how to handle these existing files. They might have been created due to  explicit user action or automatically.

* There should be error handling in case the rename/move fails. The migration should probably be aborted, but it should definitely not succeed. Unless it's just because the target name exists and we decide we can ignore that...

* `pathprovider.base64encode` specifies an altchar parameter of `+-`, which we need to take into account. (`pathprovider.base64decode` has a respective bug, as well.)

Here are some ideas; in short, I think that it's better to use an extra directory for the migration:

* Don't let the server run until successful migration.

* Migrate into a separate target directory. On successful migration, rename the target directory to become the albumart dir.

* Don't use /tmp, because we could lose the data in it.

* Don't delete the old directory if there are files in it that weren't moved. Print a warning. Or better, if the migration is otherwise complete, move these files into the target dir before renaming it.

* If the target directory already exists, assume that an aborted migration is being restarted after manual troubleshooting. Try to continue.

* If we want to rule out concurrent migrations, use a lock file in the target dir while the migration is running.

* If a filename exists in the target dir, treat the file as migrated.

* Hidden files (.*) in the source dir don't need to have their names changed.

* Warn if other files contain invalid characters, and don't change their names.

* Abort on error. Print a useful message that allows recovering manually.


I'll give these a try and come up with a script based on what you and @lzh9102 did, but right now my head's a-spinnin'... :dizzy:

**Comment by devsnd** [comment]
I'll quickly go through your notes one for one:
1.

> base64.b64decode seems to silently ignore invalid characters

Okay, so lets check `re.match('[\da-zA-Z-+]+, filename)`

2.
> Target filenames might exist if the migration loop can run concurrently

> If the server is allowed to run before the migration is successfully finished, we can't be sure how to handle these existing files

Just as you said:

> Don't let the server run until successful migration.

will fix this problem

3.
> There should be error handling in case the rename/move fails

Pythons error messages are more than enough in that case.

4.
> pathprovider.base64encode specifies an altchar parameter of +-

:+1: good catch.

5.

> Migrate into a separate target directory

Why? Renaming a file is atomic. It either succeeds or it does not. Even concurrently running migrations would work: one process crashes, the other finishes the job.

6.
All your other points are covered by my proposal: Especially with the additional regex, there is no way something is going to have a base64 decodable filename that wasnt put in this place by CM.

This is not rocket science, we're renaming a bunch of files, while making sure it only happens once per file, even if something breaks. Then we create a file that says "dont ever do it again".

**Comment by tilboerner** [comment]
The second list was meant to recap what I think should be done. Sorry if it came across as criticism; it wasn't.

> This is not rocket science, we're renaming a bunch of files, while making sure it only happens once per file, even if something breaks. Then we create a file that says "dont ever do it again".

Yeah, but also: Let's try and not screw over the user in case something goes wrong. I hate it when I update something and suddenly shit breaks. It's worse if I need to go out of my way to find out what's going on. So I'd like to:

- not break shit,
- or at least show a useful error message, and
- make it easy to recover.

The code we had so far was great and almost ready to be used, but it did none of these things as well as I'd like it to. I guess I could have done a better job of pointing out why.

> so lets check `re.match('[\da-zA-Z-+]+, filename)`

I think this would also match things like MD5 hashes with an arbitrary suffix. `^[\da-zA-Z+-]+={0,2}$` should catch out *most* invalid strings without going too overboard.


>> There should be error handling in case the rename/move fails

> Pythons error messages are more than enough in that case.

I wrote that because `except: pass` hid these messages and would have allowed the migration to succeed although it really didn't. But we get rid of this by using the regex. :)

What's more, I do not think a Python stacktrace would be enough. From a user perspective, it's not much better than a windows blue screen: it's cryptic and annoying and in your way. Let's at least say what CherryMusic was trying to do, what fell apart, and how to start to make it better, better better better better better oh! :notes:


>> Migrate into a separate target directory

> Why?

Because I think it's good practice to keep these things clean and separate if you can. In this particular case we're lucky that it's relatively easy to tell old and new apart, so it's not strictly necessary. But I think it still reduces the susceptibility to bugs. It's easier to make a subtle error and overwrite things you shouldn't if you work within the same dir, for example. Let's say the regex is a bit off, it usually works fine, but one user starts CherryMusic twice by clicking a stupid icon once too often; you're concurrently running two migrations in the same folder and bam, half the album art doesn't show up, because the file extension happens to have just the right size and hey, the hashes got a little hashier! Can you imagine the bug report? I don't wanna. :O

Separate dirs also make it a bit easier to fix things manually in the worst case. I like how pacman creates .pacnew files instead of trying to merge and leave you with the mess if something goes horribly wrong. We can at least say: this dir has the good things, that one has the bad. To cut the losses and get running again, follow these easy steps; this is how big your losses would be. If I can get that without too much overhead, I think it can be worth it.

On that note, I'll try to turn this issue into a pull request later today, so we can have some more code to comment on. And yeah, I'm grateful this is not rocket science. Migrating data is excitement enough. ;)

**Comment by 6arms1leg** [comment]
Since this issue turned into rocket science now, I felt compelled to share my opinion^^: I think performing the migration on a copy of the original directory and merge it afterwards (when everything went well) is a great idea without much overhead. :+1: 

... :monkey: :rocket: :moon:

**Comment by tilboerner** [comment]
Sorry, this took a bit more time, because I decided to do some related clean-up while I was at it. Separate pull request follows.

**Comment by devsnd** [comment]
#515 is merged. When you restart CM, it should migrate all the albumart correctly. Thanks til.
