### ISSUE TITLE
Support binding media keys to shortcut keys

### ISSUE THREAD

**Issue by cheese83** [devsnd/cherrymusic#510]
It would be very nice to be able to use the play/pause and next/previous track buttons present on many keyboards. It should be possible to bind them just like normal keyboard keys, but they can only be identified in JavaScript via the `event.key` property (see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.key), not the `event.keyCode` and `event.charCode` properties which are used by cherrymusic currently.

This is so far only supported on IE9+ and Firefox 23+, so it could be tricky to implement while still maintaining compatibility with other browsers.

**Comment by devsnd** [comment]
Hi cheese83,

Thanks for the suggestion! I think that those keyboard shortcuts could be hardcoded on top of the customizable shortcuts, since the media keys are meant for that purpose only.

If you want to experiment with that, you could just add some code to [cherrymusic.js (line 932)](https://github.com/devsnd/cherrymusic/blob/devel/res/js/cherrymusic.js#L932), where the function `keyboardShortcuts` is defined. `keyboardShortcuts` is triggered `onKeyDown`, so it should be straight forward to call any of the defined `actions` there for each respective media key.

**Comment by devsnd** [comment]
Hey cheese83!

Thanks for your contribution! :+1:
I didn't have the time to test it yet, but I'll trust you that it works. Would you be so kind and do one change before the merge? There is a part in the code that checks if no input element is focused, to make sure that the keyboard shortcuts don't interfere with the search function and so on. This however isn't the case for the media keys. Could you make sure the media keys work even though an element is focused?

Thanks again! :tiger2:

**Comment by cheese83** [comment]
You trust me more than I do! Ok, I fixed the focus behaviour.

I also discovered that shortcuts don't work reliably in Internet Explorer (and never did), because IE allows any element to be focused, not just inputs. I'm surprised no one reported that already. I might fix it later...

**Comment by devsnd** [comment]
I merged the pull-request.

If you find the time to fix the shortcuts for IE, I'd be happy to merge it! I never tried it in IE, since there is no IE for Linux ;)
