### ISSUE TITLE
Delete song from filesystem

### ISSUE THREAD

**Issue by eet6646** [devsnd/cherrymusic#511]
This option would be an administrative option, it allows the selected file to be removed from the file system (moved to recycle bin). This option could have some sort of confirmation to prevent any mishaps. 

I find this feature is lacking from most media servers as an easy way to manage your collection.

I am a new user to cherrymusic, I will check out the source when I have time and see if I could possibly contribute in the future.

**Comment by 6arms1leg** [comment]
Hello @eet6646,

thanks for your request.
In my opinion, this isn't a good idea, though. iTunes- or OwnCloud-like file manipulation is not part of what CherryMusic is meant for. It might also conflict with the file system's permissions: The user (never root) that runs CherryMusic on the server would need write access to all the media files.
Additionally, an admin user in CherryMusic might not be an administrator on the underlying system (in fact, it might not be a "real" user on that server at all).
The file path of any track is shown in CherryMusic's media browser. The "true" server administrator of the whole system can use this information to make changes to the file system. I know it's not that comfortable, but security-wise it's the safer way to go.

Personally, I consider it a feature that CherryMusic never touches your music library.
Well, let's see what others have to say...

**Comment by eet6646** [comment]
Fair point.

What information does the internal api provide? For example, would it be possible for me to create a script to call the API and get the current playing song and file path? External applications could use this information to extend the capability for the server admin.

**Comment by mikeder** [comment]
I think it would be useful to perform file manipulation from within certain installations of CherryMusic. If you run CM as a user that has write access to the underlying music base directory maybe there should be an alert of some type during the initial setup run. Then if you continue to run the server as that user you can make file changes otherwise you can run it as a read-only user and the functionality goes away. My reasoning being that my base directory is constantly getting new music added to it that sometimes needs tweaking, moving, renaming, etc.

Just my .02

**Comment by devsnd** [comment]
Hi Emmanuel and Mike,

thanks for your interest in CherryMusic! When I started to write CM, there was one thing that was clear to me: CM should not alter your music collection. The reason for that is, that there are a lot of much better tools to do the job, and creating a good file manager alone is a daunting task.

I understand however your desire to manage your music. We had the idea to create a tagging system for CM, but it has never seen the light of day. Such a system would allow you to tag files, and possible also export a list of files by tag name, to mark them for deletion, for example.

This is all speculation at this point, since I only have very little time at the moment.

> What information does the internal api provide? For example, would it be possible for me to create a script to call the API and get the current playing song and file path? External applications could use this information to extend the capability for the server admin.

It is not possible to find out which song is currently playing from the server side; All the server does is to provide the 1. to API to browse and search files and 2. to serve the static media files statically. There is not a simple way to find out who listens to what on the server side.

I was playing with the idea of providing a plugin API for CM, but yet again, there's just not enough time.

If you really want to get your hands dirty, you could change `/res/templates/mediabrowser-file.html` and add a file deletion `onclick` handler there. Which calls `api('your_new_api_function', {api_call_argument: some_variable}, success_callback)` and then define a new api handler in `cherrymusicserver/httphandler.py` and register a function that does the job on the serverside. This might work as a quick hack. :fork_and_knife: 

But if you do so, I don't think that I'll merge changes, because I really like to keep the focus of CM in playing files and not managing them on a filesystem level. I hope you understand this decision.
