### ISSUE TITLE
Support git annex -backed directories

### ISSUE THREAD

**Issue by hoxu** [devsnd/cherrymusic#518]
Currently cherrymusic seems to scan .git directory and then it proceeds to ignore all git annex symlinks:

    ERROR   : Deeply nested symlink found:

**Comment by tilboerner** [comment]
This is due to a simple and somewhat crude precaution that prevents the scanner from getting caught in link cycles. (It only ever follows top-level symlinks.)

If I understand *git annex* correctly, it replaces "annexed" files with symlinks to objects in `.git/annex`, right? As long as only files are symlinked, I think we can make this work without too much trouble. Not sure how CherryPy handles file symlinks, though. We'll look into it.

CherryMusic also shouldn't scan the `.git` directory, as it should ignore `.*` in general. But that's a separate issue. I'll open one.

**Comment by hoxu** [comment]
Yes, annexed files are just symlinks to the actual files in `.git/annex`, and git-annex creates symlinks only for files. Worth noting though that it's normal behavior that these symlinks can be broken (only some of annexed files can be actually present in a clone), so please account also for that.

So it should be enough to handle symlinks to files, and ignore broken symlinks.

**Comment by Konubinix** [comment]
For the records. I to am interested in this feature.

**Comment by tilboerner** [comment]
@hoxu, I commited a patch to the `devel` branch that should allow git-annex symlinks to be indexed.  They need to refer to valid files at the time of indexing to be included. Could I ask you to try it out and let me know if it works?

CherryMusic ignores inexistent paths by default, which is what broken symlinks are, so they shouldn't show up in the client.

**Comment by Konubinix** [comment]
Hi,
Til Boerner <notifications@github.com> writes:

> @hoxu, I commited a patch to the `devel` branch that should allow git-annex symlinks to be indexed.  They need to refer to valid files at the time of indexing to be included. Could I ask you to try it out and let me know if it works?
>
> CherryMusic ignores inexistent paths by default, which is what broken symlinks are, so they shouldn't show up in the client.

It works well. Thanks for taking this use case into account.

-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

**Comment by tilboerner** [comment]
@Konubinix, thanks for your feedback!
