### ISSUE TITLE
albumart/*thumb correlation with actual covers

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/cherrymusic#546]
Hey, 

Can someone please explain how correlates `albumart/*thumb` files with actual CM covers?
I've tried to look at `db/*db` sqlite files but didn't noticed which db and table contains those *thumbs 

```
cherrymusic]# ls albumart/
05d849f47cdf295423af770dc300919b.thumb  81a0750c88edfd2608f1630c5fb7fc6e.thumb
0c3b8ee119b8ceae1ee8c2fba803e17d.thumb  8812909769adb23c6eab6e03b848fc41.thumb
0d69fd7d3ca375502577024c523586a9.thumb  8e012eba268682c39ba6a05631e9c509.thumb
1490622e9c0b32a76c736e806222ec40.thumb  9fcceb503230d433a94a32d90f6c4354.thumb
1c029d6542cfcc27d120fe9f7a8bf4fb.thumb  c114c6b684b7333a44979caa4909df60.thumb
28f55bddf8152b69f67772b042b8c91e.thumb  c69baa594de30156c201e47dab3dc0e1.thumb
3f1141bae009190048743f6a0dec95ab.thumb  d33fb666abc3286203ff0a9aaed68f3b.thumb
56201eb783b859e5279417e2fe339923.thumb  d777b4179a7535f4953285b8da323ed6.thumb
5c40cf60f6839aa1d5daebfe23afc8c1.thumb  de1f4ecc3a44e6c76f3a4594e1e0db37.thumb
68e74ea43997862549c988dd233e1c06.thumb  ff791395c9cd7d39218527ed82e9ed71.thumb
6f1a6efe359d640c3b98768b985c48bd.thumb
```

Thanks!

**Comment by tilboerner** [comment]
It's an md5 hash of the directory path relative to your "basedir". [(code)][] 

[(code)]: https://github.com/devsnd/cherrymusic/blob/be939718dfdff04dd7607477935a4b4515c44567/cherrymusicserver/pathprovider.py#L126

For example, if your basedir is `/home/systems-rebooter/Music`, the picture for `/home/systems-rebooter/Music/Foo/Fax` will be in `md5("Foo/Fax") + ".thumb"`.

Here's a [script to look up these names](https://gist.github.com/tilboerner/2f84adbf683e411e7001) in your file system.

**Comment by systems-rebooter** [comment]
Thanks for the explanation :) And especially for the one-liner! 

I tried to get the hash of 
- regular picture
- embed picture 

using `basename` logic you wrote above, but wasn't succeeded to get same picture hash :) No crazy chars. Can using symlinks be the reason? 

Thanks!

**Comment by systems-rebooter** [comment]
@tilboerner just tried to use script, which is more convenient for comparing multiple album-arts, but still got different results with files stored in `~/.local/share/cherrymusic/albumart/` Hm..

**Comment by tilboerner** [comment]
The script shouldn't produce different results. It worked for me, but there's something wrong with it if it doesn't for you. Sorry for that, I'll see if there's time for a fix tomorrow.

**Comment by tilboerner** [comment]
Not sure what's producing the different output for you, unless `/music` is not set as basedir in your cherrymusic.conf. I've learned the hard way that encodings are a pain to deal with, but I'm not convinced that's the issue here. It just works for me, not matter what I try to break it. If you want, you could send me the output of `ls -la /music` (to `tilman.boerner` at `gmx.net`) and I'll take another look. 

> It'll be nice to renew pictures sometimes, but once md5 already exists - its not renewed properly.

I agree. It should be easier to change the pictures of individual folders to locally sourced images, or at least reset the stored picture. The only easy way to do that right now is to reset *everything* by deleting all `*.thumb` files in `.local/share/cherrymusic/albumart`

> Also, since md5 hash is kind of one way road. It would be great to store correlation in sqlite, what do you think?

I think the data about the relationship should be as close to the image data as possible. It should be hard for both data sets to diverge, and it should not be necessary to switch modes to get the complete data. So, sqlite is only marginally better than md5. Before md5, we used base64, which worked in both directions, but got too long, sometimes.

It's clear we could use something better, but that's a different issue...

**Comment by 6arms1leg** [comment]
#547 was born from this. :baby:. Just for the record...

**Comment by tilboerner** [comment]
@6arms1leg: thanks! I forgot to #mention that. :)
