### ISSUE TITLE
Windows Startup Issues

### ISSUE THREAD

**Issue by blindpet** [devsnd/cherrymusic#549]
So after I install everything I am able to run python --setup and create the account.

I can then kill the process (btw is there a shutdown server option in the interface?) and start it again with python cherrymusic

I normally make python scripts start up with NSSM or using a VBS script.

The first problem is that cherrymusic does not have a .py extension. When I try to use a vbs script I get system cannot find the file even though it is pointing to the right file. When I rename it to cherrymusic.py the VBS script starts it fine.

However when I reboot the script fails, when I try to start manually in the command prompt I get this error:

```
Traceback (most recent call last):
  File "cherrymusic", line 223, in 
    cherrymusicserver.start_server(ConfigOptions.configdict)
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 259, in start_server
    CherryMusic(cfg_override)
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 309, in __init__
    CherryMusic.create_pid_file()
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 334, in create_pid_file
    os.getpgid(int(pidfile.read()))
AttributeError: 'module' object has no attribute 'getpgid'
```

The NSSM service doesn't work either, neither with the cherrymusic or cherrymusic.py. I have the same autostart methods working with SickRage, Mylar and other python programs

As I mentioned I think it's because the pid file is in the Users/AppData folder. Perhaps it can be moved to ProgramData or in the cherrymusic folder itself somewhere?

**EDIT:** Style, Markdown.

**Comment by devsnd** [comment]
Hi blindpet!

Thanks for the report. It seems I introduced this error in https://github.com/devsnd/cherrymusic/commit/aaeaac571efe8747760bb05cd0e912e369b78145 to automatically delete the pid-file if there is no process that uses has such a process id...

I guess that warrants for a quick patch, so that windows users can start CM. Does anybody have an idea how process ids are working in windows? or how to get a similar thing like unix `/proc` in windows?

**Comment by devsnd** [comment]
Hm, it seems there is no way of doing this in windows.

[There is a library that can do such things for all platforms](https://pypi.python.org/pypi/psutil), but I'd rather not include it.

I don't even know exactly why the pid-file exists but for the tray icon, which nobody uses and as a small remedy for #195, I guess. Maybe we should just abandon the pidfile all together. Any thoughts, @tilboerner?

**Comment by blindpet** [comment]
Thanks for getting on this. If the pidfile isn't used it makes sense to abandon it, my guess is most people use this on headless machines or servers so that having a tray icon is not particularly useful but of course I'm biased.

Is there a reason the main cherrymusic file doesn't have the .py extension? It's possible with the pid issue fixed that it will run in NSSM so no need to change it yet until I've tested that update, but I am still curious why the extension is missing.

**Comment by devsnd** [comment]
Hey @blindpet,

I have fixed the issue and released a new version containing the fix (0.35.2). you can download it from the [website](http://fomori.org/cherrymusic) or here from github.

In unix systems all files can be marked as executable and will often contain a so called "shebang" that tells the system how to execute the file. CM was originally developed only for linux in mind so it was natural to call the executable `cherrymusic`, because thats prettier in the command line. On windows however, the file ending makes all the difference (double-clickable), so we might need to change that sometime...

**Comment by blindpet** [comment]
While it did seem to be working, after the 2nd reboot got this error:

**Comment by blindpet** [comment]
Another error after I Ctrl+C out of the failure above

[150420-22:51] 127.0.0.1 - - [20/Apr/2015:22:51:48] "GET /favicon.ico HTTP/1.1"
500 823 "" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/41.0.2272.118 Safari/537.36"
[150420-22:51] ERROR   : ConfigValueError: invalid value: u'None' (basedir must
be absolute path: None)
Traceback (most recent call last):
  File "c:\CherryMusic\cherrymusic", line 219, in <module>
    cherrymusicserver.update_filedb(args.update)
  File "c:\CherryMusic\cherrymusicserver\__init__.py", line 280, in update_filed
b
    cache = sqlitecache.SQLiteCache()
  File "c:\CherryMusic\cherrymusicserver\sqlitecache.py", line 88, in __init__
    self.normalize_basedir()
  File "c:\CherryMusic\cherrymusicserver\sqlitecache.py", line 457, in normalize
_basedir
    basedir = os.path.normcase(basedir)
  File "C:\Python27\lib\ntpath.py", line 46, in normcase
    return s.replace("/", "\\").lower()
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by tilboerner** [comment]
@devsnd - it's good you're asking, I came across the **PIDFile Plugin** [(doc)][] [(source)][] that's built into CherryPy a while ago and forgot about it again. Maybe we can use or steal from it? Need to check which CherryPy version introduces it.

[(doc)]: http://cherrypy.readthedocs.org/en/latest/deploy.html#pid-files
[(source)]: https://bitbucket.org/cherrypy/cherrypy/src/cb7aeeece62bb5c88eeb762c62544fc1a65b5cf6/cherrypy/process/plugins.py?at=default#cl-408

@blindpet:

> cherrymusic does not have a .py extension.

Instead of starting cherrymusic by calling the script directly, it should be possible to start the server by running the Python interpreter and giving the script file as an argument:

    python cherrymusic

The directory (folder) which contains the script needs to be the working directory in this case, or it needs to be set as the value of an environment variable called [PYTHONPATH](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH).

> (btw is there a shutdown server option in the interface?)

No. Hit `Ctrl` + `C` in the server console or terminate the process; I'm not sure about the best way to go about the latter on Windows, since I've no idea how the equivalent of signalling works there.

> for some reason the git devel branch isn't giving me the latest version.

The latest hotfix wasn't merged into devel yet; it should work now.

> (after deleting the cherrymusic in appdata folder)

Deleting the data folder (which is not the program itself) shouldn't be necessary in this case, but it should also cause no problems. Not sure where the following errors come from, but could it be that the original CherryMusic server was still running? After the hotfix, the pid check wouldn't tell you anymore, not on Windows.

If so, killing the python process that is running cherrymusic or restarting the server (machine/computer, in this case) should do the trick. You should then be able to use `--setup` again.

> `AttributeError: 'NoneType' object has no attribute 'replace'`

This is the result of a missing basedir configuration, see 
    
    [150420-22:51] ERROR   : ConfigValueError: invalid value: u'None' (basedir must be absolute path: None)

a few lines above. My guess is that the `cherrymusic.conf` file got deleted (with the data folder), and CherryMusic is using the default value, which in the case of the basedir is invalid. Same fix as above, I think.

Let us know if this helps.

**Comment by blindpet** [comment]
Now on .35.2 (just started fresh)
I am now getting new errors even when cherrymusic isn't starting until I delete the pid file after each reboot. I thought the pid file was going to be abandoned?

`C:\CherryMusic>python cherrymusic.py
============================================
Process id file C:\Users\HTPCGuides\AppData\Roaming\cherrymusic\cherrymusic.pid
already exists.
If you are sure that cherrymusic is not running, you can delete this file and re
start cherrymusic.
============================================`

Because the cherrymusic file has no extension, it prompts every reboot for how I want to open the file, when I choose python it then works but there is no way (that I know of) to make it permanent because of the lack of extension. Once I rename to cherrymusic.py both VBS and NSSM startup methods work but the pid error above persists.

**Comment by tilboerner** [comment]
> I am now getting new errors even when cherrymusic isn't starting until I delete the pid file after each reboot. I thought the pid file was going to be abandoned?

No, at this point we're merely discussing that possibility. (I also misread devsnd's hotfix, which does not remove the pid file check for windows; it removes the auto-delete feature of stale pid files.)

I think the problem you're running into is that when you shut down or reboot your machine, CherryMusic is simply killed and doesn't get a chance to delete its pid file. If you're running CherryMusic in a console window, Ctrl+C should cause the server to shutdown cleanly, although I'm unsure if Windows works this way. (There's no [SIGINT](http://en.wikipedia.org/wiki/Unix_signal#SIGINT) in Windows.) Otherwise, you could try explicitly terminating the CherryMusic's process; not sure if Windows gives it a chance to clean up first, but it might work.

We need to see if we can make CherryMusic's pid file deletion more robust; that's gonna take a moment. Until then, if Ctrl+C doesn't work for you, your best option (I can think of) is to auto-delete the pid file on boot.

> `python cherrymusic`

is not intended to fix the PID problem; I suggested it as a fix to your extension trouble. Whatever you use to run `cherrymusic` on boot, see if instead you can configure it to:

- run `python`

- with the path to the cherrymusic script file as an argument (usually goes right after the command): 

        DRIVE_LETTER:\PATH\TO\cherrymusic\cherrymusic

- and either:

    - set the working directory to the one containing the script, e.g. `DRIVE_LETTER:\PATH\TO\cherrymusic`, or

    - set an environment variable called `PYTHONPATH` (which is not the same as PATH, different name and all) and use this directory path as the value.

**Comment by blindpet** [comment]
@tilboerner I have tried everything I could think of in both the VBS and the NSSM method, neither works when the extension is missing. I still get prompted upon each startup on how to open the extensionless cherrymusic file, Windows doesn't seem to be able to remember Open With settings if the file has no extension.

The pid issue seems to be resolved, I can now reboot without closing cherrymusic with Ctrl+C and the NSSM service starts every time, so my guide will just tell the user to rename cherrymusic to cherrymusic.py. Would be nice if this wasn't the case in terms of updating with git pull but seems to be the only resolution unless you all give cherrymusic its extension ;)

**Comment by 6arms1leg** [comment]
> CM was originally developed only for linux in mind so it was natural to call the executable cherrymusic, because thats prettier in the command line. On windows however, the file ending makes all the difference (double-clickable), so we might need to change that sometime...

What about adding the *.py suffix and creating a sym-/hard link to the executable? This way we solve the auto start issue under Microsoft Windows and allow the command execution without the suffix under GNU/Linux. Am I missing something, here? :thought_balloon:

**Comment by blindpet** [comment]
@6arms1leg that sounds like a good solution

**Comment by tilboerner** [comment]
@blindpet:
> the NSSM method

Sorry to insist, but what have you tried? NSSM seems to allow exactly what I'm talking about. On https://nssm.cc/usage, there's a screenshot of a dialog with input fields for `Path` (to your python.exe), `Startup Directory` (cherrymusic program folder) and `Argument` (the start script; either just `cherrymusic`, or fully qualified with cherrymusic program folder). Did you give that a try? There's also an `Environment` tab where PYTHONPATH could be set.

If Python is in your PATH, you also should be able to open a command console (`Windows Key` + `R`, type in `cmd`, hit `Enter`), go to your cherrymusic program folder (`cd C:\BLA\BLA\cherrymusic`) and run `python cherrymusic`. That's the equivalent of entering the above values into the dialog.

Doesn't any of this work?

@6arms1leg:
> What about adding the *.py suffix and creating a sym-/hard link to the executable?

Yeah, I guess we could make `cherrymusic` a symlink to `cherrymusic.py`. That would minimize the horror of using links, but it's clunky and may still end up as two separate, identical files on Windows as far as I can tell. So it's still plenty ugly, which is why I'm reluctant. It's like a Windows tax, right? :)

How much stuff do we break if we just rename the executable, without links to keep the old filename functional?

**Comment by blindpet** [comment]
@tilboerner nssm does seem to be working without the extension after I changed the 'logon as user' so adding the symlink may not be necessary after all. The vbs script still doesn't work though but I think users can deal with just having one startup method.

**Comment by 6arms1leg** [comment]
With NSSM working now, I vote for leaving the executable as it is -- without the ugly *.py suffix. :no_good:

**Comment by blindpet** [comment]
@6arms1leg I would still argue it is a best practice / form thing to add .py but if it requires a large rewrite then maybe it's not worth it

**Comment by devsnd** [comment]
it would not require an rewrite: all there is to do is to rename the file, thats it. but the Problem would be that we'd break all of the different startup scripts and services people use to start CM.

maybe we can instead provide a windows "build" that includes a NTFS symlink or just a simple batch file that would even be smart about finding the python installation if python was not added to the %PATH%.

I still have a book about dos batch files lying around, which might become handy again for the first time in a decade.

**Comment by 6arms1leg** [comment]
>  but the Problem would be that we'd break all of the different startup scripts and services people use to start CM.

That's what I was worried about, too.

If you really think the suffix is necessary, let's go for the symlink here. :+1: 
I even think that Windows users could simply create the link manually (or rename the executable) if they want to auto start CherryMusic in Windows. A simple note in the wiki would be sufficient, in my opinion.

**Comment by blindpet** [comment]
That is what I put in the guide initially too, renaming is easy enough. I guess with a git pull update the new extensionless file is pulled and then that can just be renamed too though I haven't tested how it reacts to updates.

**Comment by tilboerner** [comment]
No renaming, then. I think we're good to close here? Otherwise, feel free to reopen.

**Comment by tilboerner** [comment]
@blindpet:
An update will overwrite/recreate the "cherrymusic" file and leave "cherrymusic.py" alone.

**Comment by 6arms1leg** [comment]
> No renaming, then. I think we're good to close here?

:+1: 
I added a [note about autostart in our wiki](https://github.com/devsnd/cherrymusic/wiki/Microsoft-Windows-setup-guide#autostart).
