### ISSUE TITLE
Displaying Japanese characters improperly

### ISSUE THREAD

**Issue by dper** [devsnd/cherrymusic#582]
I have 0.35.2 installed and working. Browsing and listening to all of my music works, except that some -- but not all -- of the Japanese songs have their song names displayed improperly.  The screenshot below shows Firefox trying to display the page as it loads.  Changing the page's character encoding doesn't fix it.  Chrome has the same issue.
![cherrymusic](https://cloud.githubusercontent.com/assets/3026536/8741056/3ff30404-2c8e-11e5-81a2-d9538c22139b.png)
In this screenshot, 17, 14, 01, and 01 are displayed improperly.

**Comment by tilboerner** [comment]
Hi Douglas, looks like we're not using the right encoding to read the tags. The issue is likely already [fixed][] in the `devel` branch, which is using a more recent [tinytag][] version. (I just updated it to an even newer one because of another bug).

Could you please try out the `devel` branch and see if the characters display correctly? Thanks!

[tinytag]: https://github.com/devsnd/tinytag/
[fixed]: https://github.com/devsnd/tinytag/commit/4bf88fb1d0837d5f42ccefe8ef59a2f302287382

**Comment by dper** [comment]
Wonderful. As you suggested, I tried the devel branch, and it works properly. Thanks!
