### ISSUE TITLE
OGG encoding problems

### ISSUE THREAD

**Issue by susnux** [devsnd/cherrymusic#583]
I have some flac files with unusual specs:
Stream #0:0: Audio: pcm_s24le, 96000 Hz, 2 channels, s32 (24 bit), 4608 kb/s

This will fail with oggenc with bit rate settings. Oggenc can not handle 96k Hz with bit rate.
But cherrymusic does not report an error, not in console and not in error.log. It delivers a 0 byte ogg file.

So either I have to edit oggenc settings to use -q instead of -b (quality of 4-5 is near 128k-160k) or enable the ffmpeg encode (is commented out it source).

To get ffmpeg working you have to edit the encoder settings to:
`Encoder('ogg', ['ffmpeg', '-i', '-', '-f', 'ogg',
                        '-c:a', 'libvorbis', '-b', 'KBITRATE',  '-'])`

And add KBITRATE to be replaced with bitrate+k (e.g. 128k).

**Comment by devsnd** [comment]
Hey Ferdinand!

Thanks for your report and investigation!

I have tried the ffmpeg OGG encoder to the list of supported encoders and added support for KBITRATE as you suggested.

But instead of your solution please try the supplied patch first, which just enables resampling using oggenc instead. If that does not work, I will enable your patch with the ffmpeg solution.
(Just as a quick explaination why I won't just merge your suggested patch: I want to keep the dependency count low, so I try not to depend to heavily on ffmpeg, but rather on the transcoder libs below)
