### ISSUE TITLE
ssl doesn't work

### ISSUE THREAD

**Issue by kas70** [devsnd/cherrymusic#593]
permissions are set like on this blog: http://fomori.org/blog/?p=687

```
[151007-15:14] ERROR   : [07/Oct/2015:15:14:45] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/wsgiserver/wsgiserver3.py", line 1560, in start
    self.tick()
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/wsgiserver/wsgiserver3.py", line 1624, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/home/cherrymusic/cherrymusic-devel/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python3.4/ssl.py", line 887, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.4/ssl.py", line 512, in __init__
    self._context.load_cert_chain(certfile, keyfile)
PermissionError: [Errno 13] Permission denied
```

**Comment by 6arms1leg** [comment]
Hello @kas70,

could you please provide us with a little more information? Just copying and pasting the error message is not enough if you want help.
Did you follow the whole guide you mentioned above? In particular, did you execute
`$ sudo usermod -a -G ssl-cert YOUR_CHERRYMUSIC_USER`
?

Of course, replace "YOUR_CHERRYMUSIC_USER" with the user that runs CherryMusic.
Also, if you are not on Debian, the group "ssl-cert" might be called differently on your system.

**Comment by kas70** [comment]
hey there, thanks for the quick reply.
yep i added my user to the group ssl-cert. i run debian.

**Comment by 6arms1leg** [comment]
Hmmm, it seems that your CherryMusic user somehow doesn't have the permissions to access your certificate and key file. Adding that user to the "ssl-cert" group should have fixed that.
Did you set the correct permissions (`root:ssl-cert`, `640`) on that files as mentioned in the guide?

Otherwise, I'm out of ideas. Debian is very fussy about correct permissions.
This issue is most likely a problem with Debian, not CherryMusic.
Again, if you want further help you probably need to post more details (e.g. CherryMusic branch and version, Debian version, etc.). Also, did you follow that guide exactly step by step?
Maybe someone else knows a solution...

**Comment by devsnd** [comment]
hi kas70,

Could you please show the file permissions of the certificate file and the folders that lead up to it? This is clearly just a file permission issue.

**Comment by kas70** [comment]
hey,
i fixed it, by repeating the steps from the blog. something was messed up (i don't know what). 
anyway, thanks for your help;)
