### ISSUE TITLE
Offline listening

### ISSUE THREAD

**Issue by edent** [devsnd/cherrymusic#604]
(Loving the server - an improvement on some of the other streaming services I feel.)

When travelling, I can't always guarantee that my laptop / phone has a consistently strong signal.

Tracks seem to load "on demand" - i.e. when Track 1 finishes, Track 2 is streamed.  If I lose connectivity while 1 is being played, 2 never loads.

Is there any way to pre-load or cache songs for offline listening?

I assume something like [Web Storage](https://developer.chrome.com/extensions/storage#property-local-QUOTA_BYTES) would have insufficient space?

(Somewhat related to #247)

**Comment by devsnd** [comment]
Hi Terence,

Thanks for the kind words!

Yes, I know what it feels like for one song stop and the next one not starting... Which is also a problem for playback with reliable internet connection, because the gaps between songs still are very noticable.

Webstorage is indeed to small for this kind of application, but I thought about leveraging the browser cache to do the work for us, and I have 3 possible solutions in mind:

 * trick the browser into loading the next song in another muted HTML5 player to cache the song for us. If we're lucky we might be able to get the browser to reuse that cached data in the "real" player instance.
 * Another way to do it would be to use 2 HTML5-players to double-buffer (load track 1 in player 1, load track 2 in player 2, load track 3 in player 1 ...) which would certainly work, but require a lot more effort.
 * Yet another solution might be to have 1 HTML5-Player per track in a playlist, which would allow for many tracks to be buffered up front.

There's currently a rewrite of CM under way which may or may not include this feature, but the rewrite will take a lot of time.

I'll close this issue for now, as this is on my personal wishlist for CM as well, but I cannot make any promises when it might land in the software.
