### ISSUE TITLE
Chrome issue on Android

### ISSUE THREAD

**Issue by demolitionfabi** [devsnd/cherrymusic#626]
Until last week my cherry music was perfectly working on my phone (Sony Xperia Z5 compact, Android 6), but since a few days ago, the music does not start playing anymore. I also tried it on the phone of a friend of mine (Nexus 5) and saw the same problem there.

In firefox mobile it works fine on my phone.

I don't know if the issue comes from a update of the Chrome browser or from an update of cherry music, because I use a cron script which automatically updates cherry music on my server.

**Comment by 6arms1leg** [comment]
Hello @demolitionfabi,

I'm sorry to hear that CherryMusic stopped working for you.
As a general advice: Please provide more information (CherryMusic version and branch, server and client OS and version, config file, log files, etc...) with your issue next time.
In this case, it is probably due to an update in Chrome, since [CherryMusic hasn't reveived any updates lately](https://github.com/devsnd/cherrymusic/commits/devel) and there are similar issues in our tracker (see #570 and #624 for example).
Im going to close this one as a duplicate. Right now, there isn't much we can do. Please see https://github.com/devsnd/cherrymusic/issues/624#issuecomment-215096927 for further details.
