### ISSUE TITLE
Music stream ended with ERR_SPDY_PROTOCOL_ERROR in Chrome

### ISSUE THREAD

**Issue by atitan** [devsnd/cherrymusic#631]
Hello,

My server environment is like this:
Fedora 24 with kernel 4.5.7
Python 3.5.1
Nginx 1.10.1
Cherrymusic 6841e74f from devel branch

I set up nginx as reverse proxy configured to use ssl and http2. Everything's fine when song starts to play. When streaming(download) comes to the end, it changes status from `200 OK` to `ERR_SPDY_PROCOTOL_ERROR` then the html5 player stopped and trying to replay the song from the beginning.
![network timeline](https://i.imgur.com/59aVCXW.png)

I've tried Chrome/51.0.2704.106, Safari 9.1.1(11601.6.17), and Firefox 47.0.1 on OSX 10.11.5.
It seems this problem only occurs in Chrome.

Serverside logs(nginx and cherrymusic) have nothing about the incident.

**Comment by devsnd** [comment]
Hm, that's interesting. But I have to admit that I'm hesitant to write a fix in the client code... The reason the song is repeating is actually a workaround for another bug in chrome. Chrome used to randomly stop the playback and the fix was to tell the client to just try again.

Could you send me a link and credentials to your setup so I can try to understand the problem?

**Comment by atitan** [comment]
I've sent you an email long time ago. Don't know if you had received it.

**Comment by devsnd** [comment]
Hey @atitan,

The mail you sent got lost in the vast stream of mails I get everyday, I am sorry about that.

I just had a look into the problem on your server, but I could not reproduce the problem as described using Firefox 47.0.1 nor using Chrome 51.0.2704.106, so I guess that this is a Browser bug. Have you updated your browser to the latest version, can you still then reproduce the HTTP 500?

**Comment by devsnd** [comment]
Hey @atitan,

I dug a little deeper and [there](http://stackoverflow.com/questions/33867014/what-mean-err-spdy-protocol-error-in-nginx) [are](https://ma.ttias.be/nginx-spdy-error-neterr_spdy_protocol_error/) [many](http://serverfault.com/questions/615321/error-code-err-spdy-protocol-error/662849) [reasons](https://trac.nginx.org/nginx/ticket/691) for this to happen. I cannot see how this is the fault of CherryMusic at this point, but I also cannot prove it is not.

You can try to install another version of cherrypy to resolve the problem, since it takes care of the HTTP-protocol layer. cherrymusic is compatible with all cherrypy versions from 3.x through the newest 6.x releases.

In any case, I don't know how to help you any futher, since I cannot reproduce the problem!

**Comment by atitan** [comment]
I've tested various versions of cherrypy but still no help. I might stick to HTTP/1.1 for temporary workaround.

Thanks for your help.

**Comment by atitan** [comment]
I think I found the solution to this problem.

Nginx connects to backend http service using HTTP 1.0 by default, which causes html5 player unable to resume playback and return the `Playback failed!` message.

Switching to HTTP 1.1 does not eliminate the SPDY_ERROR, but it allows html5 player to retry when encountering it.
