### ISSUE TITLE
[ Request ] Theming for a better looking interface?

### ISSUE THREAD

**Issue by ekianjo** [devsnd/cherrymusic#649]
Hi All, CherryMusic is a great project and it works very well for me, but I am saddened by the looks of it and the general UX (on desktop it's okay-ish, but on mobile it does not look nor plays well with the limited screen space).

Is there any way to theme cherrymusic ? If not, is there anything we can do to improve the current interface and UX elements ? Just a few changes would make it go a long way in terms of improvements. 

So, this is not an issue, but a question on how to contribute on that aspect of the project.

**Comment by devsnd** [comment]
Hey @ekianjo,

Sorry for the late reply and thanks for asking how to help, but currently I'm slowly rewriting the UI in react and the rewrite is still in a somewhat early stage. It should be possible to make UI changes once the rewrite has reached a beta-level feature-set.

Other than that: for the current code base there's some documentation of how to change stuff in the wiki: https://github.com/devsnd/cherrymusic/wiki/Development#front-end-development

Most important is the `debug=true` switch, that you can pass in the location bar of your browser, so that the client will self-compile in the browser, so you can just reload the page to see the changes you've made directly. e.g.: `https://192.168.0.1:8000?debug=true`

I'll close this issue for now, to groom the issue list a bit, but feel free to reopen it if you have any further questions!


It's dangerous to go alone, take this ⚔️

**Comment by ekianjo** [comment]
Thanks ! I guess it's probably better to wait for the rewrite :)
