### ISSUE TITLE
Wrong landing page after logout

### ISSUE THREAD

**Issue by Tjelfe** [devsnd/cherrymusic#652]
When using a non-root location (i.e. www.myserver.com/cherrymusic) logout doesn't lead back to the cherrymusic login page but to the root adress www.myserver.com.

**Comment by tilboerner** [comment]
@devsnd Could you please check out the above commit in `devel`? It's tiny, but it's client code, and it's been a while... 🐌

**Comment by devsnd** [comment]
Looks good to me. Does window.location.host always end in a slash or does this depend on whether there is a slash in the address bar?
And also, you should also commit the compiled and minified js so that everybody using devel gets the patch. 
You need to execute devscripts/deploy.py to do so if I remember correctly.

**Comment by tilboerner** [comment]
> Does window.location.host always end in a slash

No, it actually should _not_ end in a slash: that's already part of the URL's path. The code only cuts off potential leading slashes from the configured root path, so a guaranteed slash can be added without creating a duplicate. I'll add a comment there to make that clear.

> you should also commit the compiled and minified js

Right. Thanks for the reminder!
