### ISSUE TITLE
[Windows] My music is on a NAS on the local network

### ISSUE THREAD

**Issue by mapomme1108** [devsnd/cherrymusic#661]
Hello,

I have installed Cherrymusic on Windows.

My music is on a NAS on the local network.

If I create symbolic links to the NAS in the Cherrymusic music folder, Cherrymusic finds the symlinks but can not find my music files.
If I type the direct path to the network share in Cherrymusic, it does not work either.

How could I make Cherrymusic find my music on my NAS?

Thanks in advance for your help

**Comment by mapomme1108** [comment]
It works with this path //NAS/Multimedia/Musique

But I have another error 
When I click on "Browse files", there is this message = "Failed to load file browser"

**Comment by tilboerner** [comment]
> It works with this path //NAS/Multimedia/Musique

Okay, can we close this issue, or are you interested in debugging the cases where it doesn't work? Either way is fine; feel free to close this yourself. Otherwise:

In general, it's always nice to see some output if unexpected things happen, particularly from the server console. Are there error messages? Or does Cherrymusic not follow the links? To be honest, I'm not really sure how well symlinks and Python work together in Windows; I just found this [open ticket](https://bugs.python.org/issue9949) on python.org, which would be relevant.

So yeah, folks, **don't use symlinks on Windows for the time being**. Not sure what's wrong with the "direct path to the network share", though. How is that different from `//NAS/Multimedia/Musique`?

**Comment by mapomme1108** [comment]
What I call "direct path to the network share" is this : 
M:\Multimedia\Musique
and it is different to this:
//NAS/Multimedia/Musique

**Comment by tilboerner** [comment]
Thanks for clearing this up. So network-mapped drives in Windows don't behave like the actual network location, at least as far as Cherrymusic is concerned. That's good to know. (We use Linux and don't usually get much exposure to Windows-related idiosyncrasies.) 

I'm closing this issue since using the net location works. If you disagree, feel free to reopen and tell us why. :)
