### ISSUE TITLE
Several places in documentation (incorrectly) say album art fetched from Amazon by default

### ISSUE THREAD

**Issue by jperryhouts** [devsnd/cherrymusic#663]
Commit 60a291816ae06470e3b6951cbb9a9cd4dce6c143 changed the default to itunes, but didn't update documentation accordingly.

I might open this as another issue, but that option is apparently hard coded.

**Comment by tilboerner** [comment]
I updated the documentation, thanks for catching that.

> I might open this as another issue, but that option is apparently hard coded.

What do you mean by "another issue"? That the fetching method should be configurable?

**Comment by jperryhouts** [comment]
Oh, yes I was thinking that option should be configurable in the UI. Not all that important, but it would be nice. Just a thought.

Anyway, I'll close this issue now. Thanks for updating that!!

-Jonathan

**Comment by tilboerner** [comment]
@jperryhouts I made the fetch method selectable in the UI dialog. You can try it out already in the `devel` branch; otherwise, it'll be included in the next release.

**Comment by jperryhouts** [comment]
Looks good! Thanks for doing that!!

Does changing it in the dialog modify the default source for future lookups, or does it just set the method for manual downloads?

**Comment by tilboerner** [comment]
It only changes the manual lookup source. The selection will stick while the client is open; the next time the client is reloaded, it'll default back to iTunes.

It's good that you're asking; I forgot that CherryMusic can auto-fetch images - because I don't have it enabled myself, I guess. Yeah, we could include a key in the config file to change the default lookup method. Feel free to open a new ticket if you'd like, we're way off topic already. :) You can refer back to this one by mentioning its number: `#663`.

**Comment by jperryhouts** [comment]
Right. Don't worry about it for now; I might do it later if I get up some motivation. Thanks again for being so responsive!
