### ISSUE TITLE
User session is very short (24h)

### ISSUE THREAD

**Issue by regisb** [devsnd/cherrymusic#667]
When I log in my user account, the session cookie I receive expires after 24h, which is very short. Indeed, the session timeout is hardcoded to `60 * 24` minutes in `cherrymusic/__init__py`. I would like to suggest to create a configuration parameter to adjust this timeout. If not specified, the timeout will be 24h.

Before I get started coding the thing, do we agree on the proposed solution?

**Comment by devsnd** [comment]
Hi régis,

yes 24h is quite short indeed. A configuration parameter is a good option,
please go ahead and make the change, I will happily merge the pull request!



On Mar 23, 2017 2:24 PM, "Régis B." <notifications@github.com> wrote:

When I log in my user account, the session cookie I receive expires after
24h, which is very short. Indeed, the session timeout is hardcoded to 60 *
24 minutes in cherrymusic/__init__py. I would like to suggest to create a
configuration parameter to adjust this timeout. If not specified, the
timeout will be 24h.

Before I get started coding the thing, do we agree on the proposed solution?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/devsnd/cherrymusic/issues/667>, or mute the thread
