### ISSUE TITLE
Playing on Rasp Pi from NAS

### ISSUE THREAD

**Issue by n00b12345** [devsnd/cherrymusic#669]
I've a mapped NAS drive on a raspberry pi. When using Cherry Music to play songs from the NAS on the Pi, the response time and indexing processes are slow.

I completely understand if its a limitation of the Pi's hardware but I just want to make sure of that.

Thanks.

**Comment by tylerhoot** [comment]
what verion of the rpi are we talking about

**Comment by n00b12345** [comment]
@tylerhoot Raspberry Pi 2.

**Comment by tylerhoot** [comment]
thats weard atleat its not a RPI Version 1 but the rpi in general are some what slow due to all the disk access and ethernet access is done via usb so that is kinda a bottle neck but the normal responce time should not be that slow but i have not tried it my self also not including the arm processor is slow too the rpi 2 and 3 have the better luck at doing any thing with music and cherry music due to having more processor cores and a faster stock clock speed unlike the early gens of the RPI B having a single core 700mhz  ARM cpu processor speed. some one else might know more about this situation than me but that is what i can give as a input is the indexing i can expect to be slower due to being on a RPI all the disk access is based on USB or the SD card but the normal navigating i don't have a good reason why that's so slow.

**Comment by devsnd** [comment]
Hello @n00b12345,

I ran CM on a RPi 1 myself for a while and it worked well enough (even with a huge music collection), but the hard drive was connected over USB, so the performance (and especially the latency) was okay.

I guess that with the limited bandwidth of the RPi's ethernet port plus the latency added on top for whatever NFS is used, CM just will not work very well in this setup, but I doubt that any mediaplayer will work really good with that setup so I don't know how I could help you here, sorry.

I am closing this now. Please feel free to reopen this issue if you have any indication that CM *could* perform any better in this setup.
