### ISSUE TITLE
not seeing wav files

### ISSUE THREAD

**Issue by rcrath** [devsnd/cherrymusic#687]
Hi, Fresh install. probably some misunderstanding on my part, but I am  not seeing any of my wav files, though I can see them in the regular file manager, so I know they are there.  When I browse a folder with wav files in it, it says
```
No playable media files here.
```
and the -info flag show wav as installed.

```
# cherrymusic --info
CherryMusic Server 0.40.0

CherryPy: 11.0.0
Python: CPython 3.6.2
Platform: Linux-4.9.40-1-MANJARO-x86_64-with-glibc2.3.4

configuration dir:
    /home/rich/.config/cherrymusic
server data dir:
    /home/rich/.local/share/cherrymusic
static resources dir:
    /usr/share/cherrymusic/
server package dir:
    /usr/lib/python3.6/site-packages/cherrymusicserver
process working dir:
    /home/rich

locale: ('en_US', 'UTF-8'), default: ('en_US', 'UTF-8')
filesystem encoding: utf-8

Available Decoders:
    mp3 (mpg123)
    mp3 (ffmpeg)
    wma (ffmpeg)
    ogg (ffmpeg)
    oga (ffmpeg)
    flac (flac)
    aac (faad)
    m4a (ffmpeg)
    m4a (faad)
    wav (cat)
Available Encoders:
    mp3 (lame)
    aac (faac)
    m4a (faac)
    flac (flac)
    wav (cat)

(Do not parse this output.)

```

**Comment by devsnd** [comment]
Hey rich, die you enable transcoding in your config file?

On Aug 21, 2017 12:36, "Rich Rath" <notifications@github.com> wrote:

Hi, Fresh install. probably some misunderstanding on my part, but I am not
seeing any of my wav files, though I can see them in the regular file
manager, so I know they are there. When I browse a folder with wav files in
it, it says

No playable media files here.

and the -info flag show wav as installed.

# cherrymusic --info
CherryMusic Server 0.40.0

CherryPy: 11.0.0
Python: CPython 3.6.2
Platform: Linux-4.9.40-1-MANJARO-x86_64-with-glibc2.3.4

configuration dir:
    /home/rich/.config/cherrymusic
server data dir:
    /home/rich/.local/share/cherrymusic
static resources dir:
    /usr/share/cherrymusic/
server package dir:
    /usr/lib/python3.6/site-packages/cherrymusicserver
process working dir:
    /home/rich

locale: ('en_US', 'UTF-8'), default: ('en_US', 'UTF-8')
filesystem encoding: utf-8

Available Decoders:
    mp3 (mpg123)
    mp3 (ffmpeg)
    wma (ffmpeg)
    ogg (ffmpeg)
    oga (ffmpeg)
    flac (flac)
    aac (faad)
    m4a (ffmpeg)
    m4a (faad)
    wav (cat)
Available Encoders:
    mp3 (lame)
    aac (faac)
    m4a (faac)
    flac (flac)
    wav (cat)

(Do not parse this output.)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/devsnd/cherrymusic/issues/687>, or mute the thread

**Comment by rcrath** [comment]
That fixed it.  I was hoping it would play without transcoding.  thanks.

**Comment by devsnd** [comment]
Theoretically wav could be played without transcoding, bit its bandwidth
requirements are so high that I dismissed wav streaming altogether (I would
have gotten many bug reports about track load times etc etc)
